services:
  db:
    image: postgres:15
    ports:
      - '5433:5432' # aqui você muda para 5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: estelars
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
